### ISSUE TITLE
Removing course3d key in CSCI TE json list led to courses without a course3d key not showing up

### ISSUE THREAD

**Issue by amlaban65** [cis-advising-handbook/cis-advising-handbook.github.io#4]
After the latest commit (0041a7b), courses without a course3d key (ex: EESC 4620, PHIL 4720) no longer show up on the TE page
<img width="601" alt="Screen Shot 2023-11-06 at 11 08 57 AM" src="https://github.com/cis-advising-handbook/cis-advising-handbook.github.io/assets/79754427/2b6a7984-12e2-42f0-abcd-861439f3d8e1">

**Comment by devietti** [comment]
closed with #5, thanks @amlaban65!
